# Generated by Django 6.0.1 on 2026-10-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_inventoryitem_productionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='The earlier copy this one was filed to replace.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='mining.documentrecord'),
        ),
        migrations.AddField(
            model_name='inforequest',
            name='document',
            field=models.ForeignKey(blank=True, help_text='The filed document this request asks the miner to replace, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_requests', to='mining.documentrecord'),
        ),
        migrations.AlterField(
            model_name='documentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('superseded', 'Replaced')], db_index=True, default='pending', max_length=20),
        ),
    ]
