# Generated by Django 6.0.1 on 2026-09-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='logisticsapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='logisticscompany',
            options={'ordering': ['organisation__name']},
        ),
        migrations.AlterModelOptions(
            name='operatinglocation',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['registration']},
        ),
    ]
