# Generated by Django 6.0.1 on 2026-09-29 07:23

import logistics.models
from django.db import migrations, models


STATUS_MAPPINGS = {
    ("Incident", "status"): {
        "open": "open",
        "under investigation": "under_investigation",
        "under_investigation": "under_investigation",
        "resolved": "resolved",
        "closed": "closed",
    },
    ("ComplianceFinding", "status"): {
        "open": "open",
        "under review": "under_review",
        "under_review": "under_review",
        "corrective action submitted": "corrective_action_submitted",
        "corrective_action_submitted": "corrective_action_submitted",
        "cleared": "cleared",
        "closed": "cleared",
    },
    ("Delivery", "status"): {
        "pending": "pending",
        "in transit": "in_transit",
        "in_transit": "in_transit",
        "arrived": "arrived",
        "completed": "completed",
        "delivered": "completed",
        "variance": "variance_flagged",
        "variance flagged": "variance_flagged",
        "variance_flagged": "variance_flagged",
    },
    ("LogisticsPayment", "status"): {
        "not invoiced": "not_invoiced",
        "not_invoiced": "not_invoiced",
        "invoice generated": "invoice_raised",
        "invoice raised": "invoice_raised",
        "invoice_raised": "invoice_raised",
        "submitted": "submitted",
        "pending": "submitted",
        "partially paid": "part_paid",
        "part paid": "part_paid",
        "part_paid": "part_paid",
        "paid": "paid",
        "overdue": "overdue",
    },
    ("OperationsDocument", "verification_status"): {
        "verified": "verified",
        "under review": "under_review",
        "under_review": "under_review",
        "action required": "action_required",
        "action_required": "action_required",
        "rejected": "rejected",
        "expiring": "expiring",
        "expired": "expired",
    },
    ("OperationsDocument", "compliance_status"): {
        "verified": "verified",
        "under review": "under_review",
        "under_review": "under_review",
        "action required": "action_required",
        "action_required": "action_required",
        "rejected": "rejected",
        "expiring": "expiring",
        "expired": "expired",
    },
}


def normalise_status_values(apps, schema_editor):
    for (model_name, field), mapping in STATUS_MAPPINGS.items():
        model = apps.get_model("logistics", model_name)
        for pk, value in model.objects.values_list("pk", field):
            key = str(value).strip().casefold()
            if key not in mapping:
                raise ValueError(f"Unknown legacy logistics status for {model_name}.{field}: {value!r}")
            normalised = mapping[key]
            if value != normalised:
                model.objects.filter(pk=pk).update(**{field: normalised})


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_compliancefinding_movement_logisticstransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='logistics/operations/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='operationsdocument',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(normalise_status_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='compliancefinding',
            name='reference',
            field=models.CharField(default=logistics.models.compliance_finding_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='compliancefinding',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('corrective_action_submitted', 'Corrective action submitted'), ('cleared', 'Cleared')], db_index=True, default='open', max_length=40),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='reference',
            field=models.CharField(default=logistics.models.delivery_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('variance_flagged', 'Variance flagged'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reference',
            field=models.CharField(default=logistics.models.incident_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=40),
        ),
        migrations.AlterField(
            model_name='logisticspayment',
            name='reference',
            field=models.CharField(default=logistics.models.payment_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='logisticspayment',
            name='status',
            field=models.CharField(choices=[('not_invoiced', 'Not invoiced'), ('invoice_raised', 'Invoice raised'), ('submitted', 'Submitted'), ('part_paid', 'Part paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='not_invoiced', max_length=40),
        ),
        migrations.AlterField(
            model_name='movement',
            name='reference',
            field=models.CharField(default=logistics.models.movement_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='operationsdocument',
            name='compliance_status',
            field=models.CharField(choices=[('action_required', 'Action required'), ('under_review', 'Under review'), ('verified', 'Verified'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='under_review', max_length=40),
        ),
        migrations.AlterField(
            model_name='operationsdocument',
            name='reference',
            field=models.CharField(default=logistics.models.operations_document_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='operationsdocument',
            name='verification_status',
            field=models.CharField(choices=[('action_required', 'Action required'), ('under_review', 'Under review'), ('verified', 'Verified'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='under_review', max_length=40),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='reference',
            field=models.CharField(default=logistics.models.transport_request_reference, editable=False, max_length=40, unique=True),
        ),
    ]
