# Generated by Django 6.0.1 on 2026-09-29 07:23

import logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_compliancefinding_movement_logisticstransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='logistics/operations/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='operationsdocument',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='compliancefinding',
            name='reference',
            field=models.CharField(default=logistics.models.compliance_finding_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='compliancefinding',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('corrective_action_submitted', 'Corrective action submitted'), ('cleared', 'Cleared')], db_index=True, default='open', max_length=40),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='reference',
            field=models.CharField(default=logistics.models.delivery_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('variance_flagged', 'Variance flagged'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reference',
            field=models.CharField(default=logistics.models.incident_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=40),
        ),
        migrations.AlterField(
            model_name='logisticspayment',
            name='reference',
            field=models.CharField(default=logistics.models.payment_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='logisticspayment',
            name='status',
            field=models.CharField(choices=[('not_invoiced', 'Not invoiced'), ('invoice_raised', 'Invoice raised'), ('submitted', 'Submitted'), ('part_paid', 'Part paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='not_invoiced', max_length=40),
        ),
        migrations.AlterField(
            model_name='movement',
            name='reference',
            field=models.CharField(default=logistics.models.movement_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='operationsdocument',
            name='compliance_status',
            field=models.CharField(choices=[('action_required', 'Action required'), ('under_review', 'Under review'), ('verified', 'Verified'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='under_review', max_length=40),
        ),
        migrations.AlterField(
            model_name='operationsdocument',
            name='reference',
            field=models.CharField(default=logistics.models.operations_document_reference, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='operationsdocument',
            name='verification_status',
            field=models.CharField(choices=[('action_required', 'Action required'), ('under_review', 'Under review'), ('verified', 'Verified'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='under_review', max_length=40),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='reference',
            field=models.CharField(default=logistics.models.transport_request_reference, editable=False, max_length=40, unique=True),
        ),
    ]
