# Generated by Django 6.0.1 on 2026-09-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_operationsdocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('assigned', 'Assigned'), ('loading', 'Loading'), ('in_transit', 'In transit'), ('delayed', 'Delayed'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, max_length=30),
        ),
    ]
