# Generated by Django 6.0.1 on 2026-10-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_normalise_operations_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsdocument',
            name='file_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='logisticsdocument',
            name='review_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
