# Generated by Django 6.0.1 on 2026-10-01 12:11

import careers.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('pathway', models.CharField(choices=[('internship', 'Internship'), ('volunteer', 'Volunteer'), ('partnership', 'Partnership')], db_index=True, max_length=20)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('linkedin', models.URLField(max_length=300)),
                ('portfolio', models.URLField(blank=True, max_length=300)),
                ('resume', models.FileField(max_length=300, upload_to=careers.models.resume_upload_path)),
                ('headshot', models.FileField(blank=True, max_length=300, upload_to=careers.models.headshot_upload_path)),
                ('company_profile', models.FileField(blank=True, max_length=300, upload_to=careers.models.company_profile_upload_path)),
                ('answers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('info_requested', 'Information requested'), ('approved', 'Approved'), ('dashboard_active', 'Dashboard active')], db_index=True, default='draft', max_length=20)),
                ('company', models.JSONField()),
                ('agreements', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=40)),
                ('file', models.FileField(max_length=300, upload_to=careers.models.partner_document_upload_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='careers.partnerapplication')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('application', 'key'), name='careers_one_document_per_key')],
            },
        ),
    ]
