# Generated by Django 6.0.1 on 2026-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapplication',
            name='sector',
            field=models.CharField(choices=[('logistics', 'Logistics'), ('warehousing', 'Warehousing')], db_index=True, default='logistics', max_length=30),
        ),
    ]
