# Generated by Django 6.0.1 on 2026-09-07 10:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_joinrequest_employee_id_joinrequest_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('action_required', 'Action required'), ('conditionally_approved', 'Conditionally approved'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=30)),
                ('organisation_profile', models.JSONField(blank=True, default=dict)),
                ('representative', models.JSONField(blank=True, default=dict)),
                ('services', models.JSONField(blank=True, default=dict)),
                ('professional_capability', models.JSONField(blank=True, default=dict)),
                ('inspection_capability', models.JSONField(blank=True, default=dict)),
                ('conflict_declaration', models.JSONField(blank=True, default=dict)),
                ('declaration', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('conditional_requirements', models.TextField(blank=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_application', to='organisations.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_compliance_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_messages', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='compliance.complianceapplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=150)),
                ('discipline', models.CharField(blank=True, max_length=150)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('registration_number', models.CharField(blank=True, max_length=150)),
                ('cv', models.FileField(blank=True, upload_to='compliance/personnel/cv/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('certificate', models.FileField(blank=True, upload_to='compliance/personnel/certificates/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='compliance.complianceapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, upload_to='compliance/documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('request_message', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.complianceapplication')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_compliance_documents', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_compliance_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application', 'document_type'), name='unique_application_document_type')],
            },
        ),
    ]
