# Generated by Django 6.0.1 on 2026-09-08 09:54

from django.db import migrations, models

from compliance.models import generate_application_reference


def backfill_references(apps, schema_editor):
    """Give applications that predate the field a reference of their own.

    Written one row at a time rather than in bulk because each value has to be
    distinct to satisfy the unique constraint.
    """
    ComplianceApplication = apps.get_model("compliance", "ComplianceApplication")
    for application in ComplianceApplication.objects.filter(reference__isnull=True):
        application.reference = generate_application_reference()
        application.save(update_fields=["reference"])


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceapplication',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(backfill_references, migrations.RunPython.noop),
    ]
