# Generated by Django 6.0.1 on 2026-10-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_complianceapplication_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceapplication',
            name='quality_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
