# Generated by Django 6.0.1 on 2026-10-10 17:10

from django.db import migrations, models


def backfill_quality(apps, schema_editor):
    """Quality & Control is the one sector an existing application can be told
    apart by: only its flow fills quality_profile. The rest stay blank and are
    filed by the vetting desk."""
    ComplianceApplication = apps.get_model('compliance', 'ComplianceApplication')
    ComplianceApplication.objects.exclude(quality_profile={}).update(sector='quality')


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_complianceapplication_quality_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceapplication',
            name='sector',
            field=models.CharField(blank=True, choices=[('mining', 'Mining'), ('processing', 'Processing'), ('export', 'Export'), ('quality', 'Quality & Control'), ('warehousing', 'Warehousing'), ('logistics', 'Logistics'), ('marketplace', 'Marketplace')], db_index=True, max_length=20),
        ),
        migrations.RunPython(backfill_quality, migrations.RunPython.noop),
    ]
