# Generated by Django 6.0.1 on 2026-09-15 15:15

import django.core.validators
import django.db.models.deletion
import finance.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_joinrequest_employee_id_joinrequest_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=finance.models.invoice_reference, editable=False, max_length=50, unique=True)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('advance_percent', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('buyer_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_received', to='organisations.organisation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_issued', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=finance.models.payment_reference, editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('letter_of_credit', 'Letter of credit'), ('escrow', 'Escrow'), ('card', 'Card'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
