# Generated by Django 6.0.1 on 2026-09-15 15:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import ecosystem.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('export', '0002_shipment_decision_at_shipment_decision_by_and_more'),
        ('logistics', '0002_alter_driver_options_and_more'),
        ('mining', '0002_inventoryitem_productionrecord'),
        ('organisations', '0003_joinrequest_employee_id_joinrequest_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('rfq_received', 'RFQ received'), ('accepted', 'Accepted'), ('aggregation', 'Aggregation'), ('sample_requested', 'Sample requested'), ('sample_logistics', 'Sample logistics assigned'), ('sample_collected', 'Sample collected'), ('lab_received', 'Laboratory received'), ('testing', 'Testing'), ('results_published', 'Results published'), ('buyer_quality_acceptance', 'Buyer quality acceptance'), ('bulk_logistics', 'Bulk logistics assigned'), ('material_picked_up', 'Material picked up'), ('in_transit', 'In transit'), ('warehouse_received', 'Warehouse / processor received'), ('processing_started', 'Processing started'), ('processing_completed', 'Processing completed'), ('output_recorded', 'Output tonnage recorded'), ('post_processing_quality', 'Post processing quality'), ('export_compliance', 'Export compliance'), ('export_ready', 'Export ready'), ('shipped', 'Shipped'), ('buyer_destination', 'Buyer destination'), ('delivered', 'Delivered'), ('payment_settlement', 'Payment / settlement')], max_length=30)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mine_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='mining.minesite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=ecosystem.models.batch_reference, editable=False, max_length=50, unique=True)),
                ('mineral', models.CharField(max_length=120)),
                ('tonnes', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('stage', models.CharField(choices=[('stockpile', 'Stockpile'), ('allocated', 'Allocated'), ('in_transit', 'In transit'), ('warehouse', 'Warehouse'), ('processing', 'Processing'), ('export_ready', 'Export ready'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], db_index=True, default='stockpile', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('mine_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_batches', to='mining.minesite')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=ecosystem.models.move_reference, editable=False, max_length=50, unique=True)),
                ('kind', models.CharField(choices=[('sample', 'Sample'), ('bulk', 'Bulk')], max_length=10)),
                ('carrier_name', models.CharField(blank=True, help_text='Free-text carrier when no registered LogisticsCompany applies.', max_length=200)),
                ('vehicle', models.CharField(blank=True, max_length=120)),
                ('driver', models.CharField(blank=True, max_length=120)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('tonnes', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], db_index=True, default='assigned', max_length=15)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('carrier_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecosystem_moves', to='logistics.logisticscompany')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_moves', to='ecosystem.materialbatch')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Rfq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=ecosystem.models.rfq_reference, editable=False, max_length=50, unique=True)),
                ('mineral', models.CharField(max_length=120)),
                ('grade_spec', models.CharField(blank=True, max_length=255)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='t', max_length=20)),
                ('indicative_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('incoterm', models.CharField(blank=True, max_length=50)),
                ('destination', models.CharField(blank=True, max_length=150)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('respond_by', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('partially_accepted', 'Partially accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='open', max_length=25)),
                ('committed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs_sent', to='organisations.organisation')),
                ('seller_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs_received', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=ecosystem.models.transaction_reference, editable=False, max_length=50, unique=True)),
                ('mineral', models.CharField(max_length=120)),
                ('grade_spec', models.CharField(blank=True, max_length=255)),
                ('committed_tonnes', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('aggregated_tonnes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('incoterm', models.CharField(blank=True, max_length=50)),
                ('destination', models.CharField(blank=True, max_length=150)),
                ('stage', models.CharField(choices=[('rfq_received', 'RFQ received'), ('accepted', 'Accepted'), ('aggregation', 'Aggregation'), ('sample_requested', 'Sample requested'), ('sample_logistics', 'Sample logistics assigned'), ('sample_collected', 'Sample collected'), ('lab_received', 'Laboratory received'), ('testing', 'Testing'), ('results_published', 'Results published'), ('buyer_quality_acceptance', 'Buyer quality acceptance'), ('bulk_logistics', 'Bulk logistics assigned'), ('material_picked_up', 'Material picked up'), ('in_transit', 'In transit'), ('warehouse_received', 'Warehouse / processor received'), ('processing_started', 'Processing started'), ('processing_completed', 'Processing completed'), ('output_recorded', 'Output tonnage recorded'), ('post_processing_quality', 'Post processing quality'), ('export_compliance', 'Export compliance'), ('export_ready', 'Export ready'), ('shipped', 'Shipped'), ('buyer_destination', 'Buyer destination'), ('delivered', 'Delivered'), ('payment_settlement', 'Payment / settlement')], db_index=True, default='rfq_received', max_length=30)),
                ('buyer_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_buyer', to='organisations.organisation')),
                ('export_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecosystem_transactions', to='export.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
