# Generated by Django 6.0.1 on 2026-09-15 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecosystem', '0001_initial'),
        ('finance', '0001_initial'),
        ('mining', '0002_inventoryitem_productionrecord'),
        ('organisations', '0003_joinrequest_employee_id_joinrequest_job_title'),
        ('processing', '0003_alter_compliancereport_options_compliancereport_kind_and_more'),
        ('quality', '0001_initial'),
        ('warehousing', '0003_inventorylot_actual_weighbridge_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='finance_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecosystem_transactions', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mine_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecosystem_transactions', to='mining.minesite'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecosystem_transactions', to='processing.traceabilityrun'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quality_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecosystem_transactions', to='quality.sample'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ecosystem.rfq'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_seller', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='warehousing_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecosystem_transactions', to='warehousing.inventorylot'),
        ),
        migrations.AddField(
            model_name='materialbatch',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='ecosystem.transaction'),
        ),
        migrations.AddField(
            model_name='logisticsmove',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_moves', to='ecosystem.transaction'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commitment', to='ecosystem.transaction'),
        ),
        migrations.AddField(
            model_name='transactionstageevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionstageevent',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='ecosystem.transaction'),
        ),
        migrations.AddConstraint(
            model_name='transactionstageevent',
            constraint=models.UniqueConstraint(fields=('transaction', 'stage'), name='unique_transaction_stage_event'),
        ),
    ]
