# Generated by Django 6.0.1 on 2026-09-09 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processingdocument',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processingdocument',
            name='review_state',
            field=models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('info_requested', 'Information requested'), ('flagged', 'Flagged')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='processingdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_processing_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
