# Generated by Django 6.0.1 on 2026-09-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_processingdocument_review_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancereport',
            options={'ordering': ['-generated_on', '-created_at']},
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='kind',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='reference',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
