# Generated by Django 6.0.1 on 2026-09-14 11:43

import django.core.validators
import django.db.models.deletion
import uuid
import warehousing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_joinrequest_employee_id_joinrequest_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('ambient', 'Ambient'), ('cold_chain', 'Cold chain'), ('bonded', 'Bonded'), ('hazmat', 'Hazardous materials'), ('yard', 'Open yard')], max_length=80)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_unit', models.CharField(choices=[('tonnes', 'Tonnes'), ('sqm', 'Square metres'), ('pallets', 'Pallets')], default='tonnes', max_length=20)),
                ('fire_certificate_expires_on', models.DateField(blank=True, null=True)),
                ('insurance_expires_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseOperator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=warehousing.models.warehouse_reference, editable=False, max_length=50, unique=True)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('warehouse_license_number', models.CharField(blank=True, max_length=100)),
                ('license_expires_on', models.DateField(blank=True, null=True)),
                ('services', models.JSONField(default=list)),
                ('storage_categories', models.JSONField(default=list)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_profile', to='organisations.organisation')),
            ],
            options={
                'ordering': ['organisation__name'],
            },
        ),
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('storage_type', models.CharField(max_length=80)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_unit', models.CharField(default='tonnes', max_length=20)),
                ('restricted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='warehousing.facility')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehousing.warehouseoperator')),
            ],
            options={
                'ordering': ['facility__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousing.warehouseoperator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=warehousing.models.lot_reference, editable=False, max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('batch_number', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='tonnes', max_length=30)),
                ('received_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('stored', 'Stored'), ('quarantined', 'Quarantined'), ('released', 'Released'), ('dispatched', 'Dispatched')], default='received', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='warehousing.facility')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='warehousing.storagezone')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='warehousing.warehouseoperator')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_type', models.CharField(max_length=80)),
                ('inspected_on', models.DateField()),
                ('inspector_name', models.CharField(max_length=200)),
                ('outcome', models.CharField(choices=[('passed', 'Passed'), ('attention', 'Attention'), ('failed', 'Failed')], default='passed', max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('next_due_on', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='warehousing.facility')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='warehousing.warehouseoperator')),
            ],
            options={
                'ordering': ['-inspected_on'],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='warehousing.warehouseoperator'),
        ),
        migrations.CreateModel(
            name='WarehousingAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('reviewer', 'Reviewer'), ('regulator', 'Regulator')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='warehousing.warehouseoperator')),
            ],
        ),
        migrations.CreateModel(
            name='WarehousingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('awaiting_information', 'Awaiting information'), ('conditionally_approved', 'Conditionally approved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('policy_version', models.CharField(default='warehousing-baseline-v1', max_length=100)),
                ('domain_weights', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehousing_reviews', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='warehousing.warehouseoperator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('items', models.JSONField(default=list)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('accepted', 'Accepted')], default='open', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='warehousing.warehousingapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomainReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('operator', 'Warehouse operator'), ('facility', 'Facility and location'), ('storage', 'Storage controls'), ('inventory', 'Inventory traceability'), ('safety', 'Fire, HSE and security'), ('quality', 'Quality assurance'), ('equipment', 'Equipment calibration'), ('logistics', 'Inbound and outbound logistics')], max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('applicable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('attention', 'Attention'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='warehousing.warehousingapplication')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='WarehousingCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('domain', models.CharField(blank=True, choices=[('operator', 'Warehouse operator'), ('facility', 'Facility and location'), ('storage', 'Storage controls'), ('inventory', 'Inventory traceability'), ('safety', 'Fire, HSE and security'), ('quality', 'Quality assurance'), ('equipment', 'Equipment calibration'), ('logistics', 'Inbound and outbound logistics')], max_length=30)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='warehousing.warehousingapplication')),
                ('cleared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehousingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('operator', 'Warehouse operator'), ('facility', 'Facility and location'), ('storage', 'Storage controls'), ('inventory', 'Inventory traceability'), ('safety', 'Fire, HSE and security'), ('quality', 'Quality assurance'), ('equipment', 'Equipment calibration'), ('logistics', 'Inbound and outbound logistics')], max_length=30)),
                ('document_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='warehousing/evidence/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehousing.warehousingapplication')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='warehousing.warehousingcondition')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='warehousing.inventorylot')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='warehousing.informationrequest')),
                ('documents', models.ManyToManyField(to='warehousing.warehousingdocument')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehousingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(default='register', max_length=30)),
                ('warehouse_ids', models.JSONField(default=list)),
                ('content', models.TextField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='storagezone',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='unique_warehouse_zone'),
        ),
        migrations.AddConstraint(
            model_name='warehousingaccessgrant',
            constraint=models.UniqueConstraint(fields=('warehouse', 'user', 'role'), name='unique_warehousing_access_grant'),
        ),
        migrations.AddConstraint(
            model_name='domainreview',
            constraint=models.UniqueConstraint(fields=('application', 'key'), name='unique_warehousing_domain'),
        ),
        migrations.AddConstraint(
            model_name='warehousingdocument',
            constraint=models.UniqueConstraint(fields=('application', 'document_type', 'version'), name='unique_warehousing_document_version'),
        ),
        migrations.AddConstraint(
            model_name='warehousingdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('application', 'document_type'), name='unique_current_warehousing_document'),
        ),
    ]
