# Generated by Django 6.0.1 on 2026-09-15 13:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='bay_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='built_area',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='facility',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='fire_system_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='laboratory_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='land_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='facility',
            name='loading_dock_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='security_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='weighbridge_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouseoperator',
            name='annual_turnover',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouseoperator',
            name='bankers',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='warehouseoperator',
            name='company_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='warehouseoperator',
            name='directors',
            field=models.JSONField(blank=True, default=list, help_text='[{name, role, bvn_verified}]'),
        ),
        migrations.AddField(
            model_name='warehouseoperator',
            name='head_office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouseoperator',
            name='incorporated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseoperator',
            name='mineral_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='warehouseoperator',
            name='shareholding',
            field=models.JSONField(blank=True, default=list, help_text='[{holder, percent}]'),
        ),
        migrations.AddField(
            model_name='warehouseoperator',
            name='staff_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseoperator',
            name='trading_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('issued_on', models.DateField()),
                ('expires_on', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('conditional', 'Conditional'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=20)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='warehousing.warehousingapplication')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='warehousing.facility')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='warehousing.warehouseoperator')),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('safety', 'Safety'), ('environmental', 'Environmental'), ('security', 'Security'), ('stock_integrity', 'Stock integrity')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('occurred_on', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under investigation'), ('closed', 'Closed')], default='open', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='warehousing.facility')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='warehousing.inventorylot')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='warehousing.warehouseoperator')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('source', models.CharField(blank=True, max_length=150)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_alerts', to='warehousing.facility')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_alerts', to='warehousing.warehouseoperator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by_name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=255)),
                ('declared_quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_weighbridge_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='tonnes', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending authorisation'), ('authorised', 'Authorised'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('authorised_at', models.DateTimeField(blank=True, null=True)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_requests', to='warehousing.inventorylot')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_requests', to='warehousing.warehouseoperator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
