# Generated by Django 6.0.1 on 2026-09-15 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0002_inspector_facility_bay_count_facility_built_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylot',
            name='actual_weighbridge_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Measured weighbridge quantity at intake, if weighed.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Declared quantity at intake.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
