# Generated by Django 6.0.1 on 2026-09-14 11:14

import django.core.validators
import django.db.models.deletion
import export.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_joinrequest_employee_id_joinrequest_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('awaiting_information', 'Awaiting information'), ('conditionally_approved', 'Conditionally approved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('policy_version', models.CharField(default='export-baseline-v1', max_length=100)),
                ('domain_weights', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('domain', models.CharField(blank=True, choices=[('exporter', 'Exporter profile'), ('product', 'Product classification'), ('buyer', 'Buyer and destination'), ('shipment', 'Shipment plan'), ('customs', 'Customs documentation'), ('quality', 'Quality certificate'), ('logistics', 'Logistics handoff'), ('finance', 'Finance and proceeds')], max_length=30)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='export.exportapplication')),
                ('cleared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('exporter', 'Exporter profile'), ('product', 'Product classification'), ('buyer', 'Buyer and destination'), ('shipment', 'Shipment plan'), ('customs', 'Customs documentation'), ('quality', 'Quality certificate'), ('logistics', 'Logistics handoff'), ('finance', 'Finance and proceeds')], max_length=30)),
                ('document_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='export/evidence/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='export.exportapplication')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='export.exportcondition')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=export.models.exporter_reference, editable=False, max_length=50, unique=True)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('export_license_number', models.CharField(blank=True, max_length=100)),
                ('license_expires_on', models.DateField(blank=True, null=True)),
                ('destinations', models.JSONField(default=list)),
                ('product_categories', models.JSONField(default=list)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exporter_profile', to='organisations.organisation')),
            ],
            options={
                'ordering': ['organisation__name'],
            },
        ),
        migrations.AddField(
            model_name='exportapplication',
            name='exporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='export.exporter'),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('tax_identifier', models.CharField(blank=True, max_length=100)),
                ('screening_status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='export.exporter')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExportReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(default='register', max_length=30)),
                ('exporter_ids', models.JSONField(default=list)),
                ('content', models.TextField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('items', models.JSONField(default=list)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('accepted', 'Accepted')], default='open', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='export.exportapplication')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export.exporter')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hs_code', models.CharField(max_length=20)),
                ('origin_state', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='tonnes', max_length=30)),
                ('annual_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('controlled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='export.exporter')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(to='export.exportdocument')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='export.informationrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=export.models.shipment_reference, editable=False, max_length=50, unique=True)),
                ('destination_country', models.CharField(max_length=100)),
                ('port_of_loading', models.CharField(max_length=120)),
                ('port_of_discharge', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='tonnes', max_length=30)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('expected_ship_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ready', 'Ready'), ('cleared', 'Cleared'), ('shipped', 'Shipped'), ('held', 'Held'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='export.buyer')),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='export.exporter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='export.product')),
            ],
            options={
                'ordering': ['-expected_ship_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exportdocument',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='export.shipment'),
        ),
        migrations.CreateModel(
            name='DomainReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('exporter', 'Exporter profile'), ('product', 'Product classification'), ('buyer', 'Buyer and destination'), ('shipment', 'Shipment plan'), ('customs', 'Customs documentation'), ('quality', 'Quality certificate'), ('logistics', 'Logistics handoff'), ('finance', 'Finance and proceeds')], max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('applicable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('attention', 'Attention'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='export.exportapplication')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('application', 'key'), name='unique_export_domain')],
            },
        ),
        migrations.CreateModel(
            name='ExportAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('reviewer', 'Reviewer'), ('regulator', 'Regulator')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='export.exporter')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exporter', 'user', 'role'), name='unique_export_access_grant')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('exporter', 'hs_code', 'name'), name='unique_export_product'),
        ),
        migrations.AddConstraint(
            model_name='exportdocument',
            constraint=models.UniqueConstraint(fields=('application', 'document_type', 'version'), name='unique_export_document_version'),
        ),
        migrations.AddConstraint(
            model_name='exportdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('application', 'document_type'), name='unique_current_export_document'),
        ),
    ]
