# Generated by Django 6.0.1 on 2026-09-15 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='decision_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='decision_outcome',
            field=models.CharField(blank=True, choices=[('cleared', 'Cleared'), ('conditionally_cleared', 'Conditionally cleared'), ('declined', 'Declined')], max_length=25),
        ),
        migrations.AddField(
            model_name='shipment',
            name='decision_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ShipmentChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('exporter', 'Exporter profile'), ('product', 'Product classification'), ('buyer', 'Buyer and destination'), ('shipment', 'Shipment plan'), ('customs', 'Customs documentation'), ('quality', 'Quality certificate'), ('logistics', 'Logistics handoff'), ('finance', 'Finance and proceeds')], max_length=30)),
                ('label', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('pass', 'Pass'), ('open', 'Open'), ('fail', 'Fail')], default='open', max_length=10)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='export.shipment')),
            ],
            options={
                'ordering': ['domain', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentNonConformity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('exporter', 'Exporter profile'), ('product', 'Product classification'), ('buyer', 'Buyer and destination'), ('shipment', 'Shipment plan'), ('customs', 'Customs documentation'), ('quality', 'Quality certificate'), ('logistics', 'Logistics handoff'), ('finance', 'Finance and proceeds')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='major', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('closed', 'Closed')], default='open', max_length=15)),
                ('response', models.TextField(blank=True)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformities', to='export.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
