# Generated by Django 6.0.1 on 2026-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_country_user_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_role',
            field=models.CharField(blank=True, choices=[('compliance-org', 'Mining Compliance Organisation'), ('compliance-officer', 'Mining Compliance Officer'), ('regulatory-org', 'Regulatory / Oversight Organisation'), ('regulatory-officer', 'Regulatory / Oversight Officer'), ('independent', 'Independent Mining Compliance Professional')], max_length=40),
        ),
    ]
