# Generated by Django 6.0.1 on 2026-09-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_socialidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portal',
            field=models.CharField(blank=True, choices=[('compliance', 'Compliance'), ('miner', 'Miner Hub')], max_length=20),
        ),
    ]
