# Generated by Django 6.0.1 on 2026-09-12 15:21

import django.db.models.deletion
import django.utils.timezone
import quality.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_joinrequest_employee_id_joinrequest_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('buyer_org', models.CharField(blank=True, max_length=255)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('limits', models.JSONField(blank=True, default=list)),
                ('buyer_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisations.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QualityApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=quality.models.application_reference, editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In review'), ('info_requested', 'Info requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('organisation_data', models.JSONField(blank=True, default=dict)),
                ('capability_data', models.JSONField(blank=True, default=dict)),
                ('laboratory_data', models.JSONField(blank=True, default=dict)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('audit', models.JSONField(blank=True, default=list)),
                ('decision_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_applications', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityNonConformity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=quality.models.nc_reference, editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raised_by', models.CharField(blank=True, max_length=255)),
                ('against', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('capa_submitted', 'CAPA submitted'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('capa', models.JSONField(blank=True, default=list)),
                ('raised_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'quality non-conformities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=quality.models.sample_reference, editable=False, max_length=50, unique=True)),
                ('material', models.CharField(max_length=120)),
                ('lot', models.CharField(blank=True, max_length=120)),
                ('mine_site', models.CharField(blank=True, max_length=200)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('mass_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('miner_org', models.CharField(blank=True, max_length=255)),
                ('partner_org', models.CharField(blank=True, max_length=255)),
                ('buyer_org', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('in_transit', 'In transit'), ('received', 'Received'), ('testing', 'Testing'), ('reviewed', 'Reviewed'), ('certified', 'Certified'), ('rejected', 'Rejected')], db_index=True, default='registered', max_length=20)),
                ('custody', models.JSONField(blank=True, default=list)),
                ('test_request', models.JSONField(blank=True, default=dict, null=True)),
                ('results', models.JSONField(blank=True, default=list)),
                ('quality_review', models.JSONField(blank=True, default=dict, null=True)),
                ('audit', models.JSONField(blank=True, default=list)),
                ('buyer_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='quality.buyerspec')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=quality.models.certificate_reference, editable=False, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('draft', 'Draft')], db_index=True, default='active', max_length=20)),
                ('verification_hash', models.CharField(blank=True, max_length=128)),
                ('scans', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='quality.sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
