# Generated by Django 6.0.1 on 2026-10-05 11:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_sample_organisations(apps, schema_editor):
    Organisation = apps.get_model('organisations', 'Organisation')
    Sample = apps.get_model('quality', 'Sample')
    for sample in Sample.objects.select_related('buyer_spec').all():
        updates = []
        if sample.miner_org and not sample.miner_organisation_id:
            org = Organisation.objects.filter(name__iexact=sample.miner_org).first()
            if org:
                sample.miner_organisation_id = org.id
                updates.append('miner_organisation')
        if sample.partner_org and not sample.partner_organisation_id:
            org = Organisation.objects.filter(name__iexact=sample.partner_org).first()
            if org:
                sample.partner_organisation_id = org.id
                updates.append('partner_organisation')
        if not sample.buyer_organisation_id:
            org = None
            if sample.buyer_spec_id and sample.buyer_spec.buyer_organisation_id:
                org = sample.buyer_spec.buyer_organisation
            elif sample.buyer_org:
                org = Organisation.objects.filter(name__iexact=sample.buyer_org).first()
            if org:
                sample.buyer_organisation_id = org.id
                updates.append('buyer_organisation')
        if updates:
            sample.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_alter_organisation_organisation_type'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='buyer_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='sample',
            name='miner_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='sample',
            name='partner_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisations.organisation'),
        ),
        migrations.CreateModel(
            name='QualityNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('event', models.CharField(db_index=True, max_length=80)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quality.qualityapplication')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quality.certificate')),
                ('non_conformity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quality.qualitynonconformity')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_notifications', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quality.sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(upload_to='quality/application-documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'zip'])])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='quality.qualityapplication')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('application', 'document_id'), name='unique_quality_application_document')],
            },
        ),
        migrations.RunPython(backfill_sample_organisations, migrations.RunPython.noop),
    ]
