# Generated by Django 6.0.1 on 2026-10-10 14:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import quality.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_complianceapplication_quality_profile'),
        ('organisations', '0004_alter_organisation_organisation_type'),
        ('quality', '0003_seed_reference_buyer_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityapplication',
            name='compliance_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_application', to='compliance.complianceapplication'),
        ),
        migrations.CreateModel(
            name='QualityProfessionalApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=quality.models.professional_reference, editable=False, max_length=50, unique=True)),
                ('role', models.CharField(default='officer_inspector', max_length=40)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In review'), ('info_requested', 'Info requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('personal', models.JSONField(blank=True, default=dict)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('capability', models.JSONField(blank=True, default=dict)),
                ('experience', models.JSONField(blank=True, default=dict)),
                ('declaration', models.JSONField(blank=True, default=dict)),
                ('audit', models.JSONField(blank=True, default=list)),
                ('decision_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_professional_applications', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_professional_applications', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityProfessionalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='quality/professional-documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'zip'])])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='quality.qualityprofessionalapplication')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('application', 'document_type'), name='unique_quality_professional_document')],
            },
        ),
    ]
