# Generated by Django 6.0.1 on 2026-09-04 11:54

import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('organisation_type', models.CharField(choices=[('mining_company', 'Mining company'), ('compliance_partner', 'Compliance partner'), ('regulator', 'Regulator'), ('laboratory', 'Laboratory'), ('inspection_body', 'Inspection body')], db_index=True, max_length=30)),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tax_identifier', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='draft', max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('country', 'registration_number'), name='unique_org_registration_per_country')],
            },
        ),
        migrations.CreateModel(
            name='OrganisationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('reviewer', 'Reviewer'), ('inspector', 'Inspector'), ('member', 'Member')], default='member', max_length=20)),
                ('token', models.CharField(default=secrets.token_urlsafe, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_organisation_invitations', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('reviewer', 'Reviewer'), ('inspector', 'Inspector'), ('member', 'Member')], default='member', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_join_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_join_requests', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organisation', 'requester'), name='unique_pending_join_request')],
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('reviewer', 'Reviewer'), ('inspector', 'Inspector'), ('member', 'Member')], default='member', max_length=20)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'user'), name='unique_organisation_member')],
            },
        ),
    ]
