# Generated by Django 6.0.1 on 2026-09-07 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='beldium_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisationmembership',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisationmembership',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='requested_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('reviewer', 'Reviewer'), ('inspector', 'Inspector'), ('member', 'Member'), ('compliance_manager', 'Compliance Manager'), ('mining_compliance_officer', 'Mining Compliance Officer'), ('mining_engineer', 'Mining Engineer'), ('geologist', 'Geologist'), ('environmental_specialist', 'Environmental Specialist'), ('hse_specialist', 'HSE Specialist'), ('legal_regulatory_specialist', 'Legal / Regulatory Specialist'), ('analyst', 'Analyst'), ('read_only', 'Read Only User'), ('other', 'Other')], default='member', max_length=40),
        ),
        migrations.AlterField(
            model_name='organisationinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('reviewer', 'Reviewer'), ('inspector', 'Inspector'), ('member', 'Member'), ('compliance_manager', 'Compliance Manager'), ('mining_compliance_officer', 'Mining Compliance Officer'), ('mining_engineer', 'Mining Engineer'), ('geologist', 'Geologist'), ('environmental_specialist', 'Environmental Specialist'), ('hse_specialist', 'HSE Specialist'), ('legal_regulatory_specialist', 'Legal / Regulatory Specialist'), ('analyst', 'Analyst'), ('read_only', 'Read Only User'), ('other', 'Other')], default='member', max_length=40),
        ),
        migrations.AlterField(
            model_name='organisationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('reviewer', 'Reviewer'), ('inspector', 'Inspector'), ('member', 'Member'), ('compliance_manager', 'Compliance Manager'), ('mining_compliance_officer', 'Mining Compliance Officer'), ('mining_engineer', 'Mining Engineer'), ('geologist', 'Geologist'), ('environmental_specialist', 'Environmental Specialist'), ('hse_specialist', 'HSE Specialist'), ('legal_regulatory_specialist', 'Legal / Regulatory Specialist'), ('analyst', 'Analyst'), ('read_only', 'Read Only User'), ('other', 'Other')], default='member', max_length=40),
        ),
    ]
