# Generated by Django 6.0.1 on 2026-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_beldium_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='job_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
