# Generated by Django 6.0.1 on 2026-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_joinrequest_employee_id_joinrequest_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_type',
            field=models.CharField(choices=[('mining_company', 'Mining company'), ('logistics_company', 'Logistics company'), ('compliance_partner', 'Compliance partner'), ('regulator', 'Regulator'), ('laboratory', 'Laboratory'), ('inspection_body', 'Inspection body')], db_index=True, max_length=30),
        ),
    ]
